# -*- coding: utf-8 -*-
"""
/***************************************************************************
 serviciosIDEE2QGIS
                                 A QGIS plugin
 Permite cargar a QGIS lso servicios de la IDEE a partir del Catálogo CSW
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-15
        copyright            : (C) 2025 by ingenieroGeomatico
        email                :  aurearagon@gmail.com 
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load serviciosIDEE2QGIS class from file serviciosIDEE2QGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .serviciosIDEE2QGIS import serviciosIDEE2QGIS
    return serviciosIDEE2QGIS(iface)
