# -*- coding: utf-8 -*-
"""
/***************************************************************************
 serviciosIDEE2QGIS
                                 A QGIS plugin
 Permite cargar a QGIS lso servicios de la IDEE a partir del Catálogo CSW
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-15
        git sha              : $Format:%H$
        copyright            : (C) 2025 by ingenieroGeomatico
        email                :  aurearagon@gmail.com 
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

from qgis.core import QgsRasterLayer, QgsVectorLayer, QgsProject

from PyQt5.QtWidgets import QTableWidgetItem, QCheckBox
from PyQt5.QtCore import Qt

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .serviciosIDEE2QGIS_dialog import serviciosIDEE2QGISDialog
import os.path

import sys
import os

# Añadimos la ruta a la librería
plugin_dir = os.path.dirname(__file__)
sys.path.append(os.path.join(plugin_dir, "libs/owslib_0_34_1"))

# Ahora podemos importar owslib
from owslib_.csw import CatalogueServiceWeb


CSW_URL = 'https://www.idee.es/csw-codsi-idee/srv/spa/csw'
# Posibles URL que pueden servir:
# https://www.idee.es/csw-inspire-idee/srv/spa/q?_content_type=json&bucket=s101&facet.q=type/service&fast=index&from=1&keyword=WMS%20or%20Web%20Map%20Service%20or%20WMTS%20or%20Web%20Map%20Tile%20Service%20or%20TMS%20or%20MVT%20or%20Features%20WFS&resultType=details&sortBy=title&sortOrder=asc&to=9
# https://www.idee.es/csw-codsi-idee/srv/spa/csw?request=GetRecords&service=CSW&version=2.0.2&typeNames=csw:Record&resultType=results
# https://www.idee.es/csw-codsi-idee/srv/spa/csw?request=GetCapabilities&service=CSW&version=2.0.2
# https://www.idee.es/csw-codsi-idee/srv/spa/catalog.search#/search?isTemplate=n&resourceTemporalDateRange=%7B%22range%22:%7B%22resourceTemporalDateRange%22:%7B%22gte%22:null,%22lte%22:null,%22relation%22:%22intersects%22%7D%7D%7D&sortBy=relevance&sortOrder=&from=1&to=30
# https://www.idee.es/csw-codsi-idee/srv/spa/csw?request=GetRecords&resultType=results&service=CSW&version=2.0.2&namespace=xmlns(csw=http://www.opengis.net/cat/csw/2.0.2),xmlns(gmd=http://www.isotc211.org/2005/gmd)&typeNames=gmd:MD_Metadata&outputFormat=application/xml&outputSchema=http://www.isotc211.org/2005/gmd&startPosition=1&maxRecords=40&elementSetName=summary&typeNames=csw:Record

def get_idee_services(batch_size=50):
    """
    Obtiene todos los servicios del catálogo CSW de la IDEE
    que tienen un esquema (scheme) distinto de None.
    Devuelve una lista de diccionarios con: title, abstract, url y tipo.
    """
    servicios = []

    try:
        csw = CatalogueServiceWeb(CSW_URL, timeout=30)
        # Pedimos solo 1 registro para obtener el total
        csw.getrecords2(constraints=[], maxrecords=1)
        total = csw.results['matches']
        print(f"Total de registros en el catálogo: {total}")

        for start in range(0, total, batch_size):
            csw.getrecords2(constraints=[], startposition=start+1, maxrecords=batch_size)
            for rec_id, rec in csw.records.items():
                # Buscamos la primera referencia con scheme distinto de None
                url = None
                tipo = None
                for ref in rec.references:
                    if ref['scheme'] is not None:
                        url = ref['url']
                        if 'WMS' in ref['scheme'].upper():
                            tipo = 'WMS'
                        elif 'WFS' in ref['scheme'].upper():
                            tipo = 'WFS'
                        else:
                            tipo = 'Otro'
                        break
                if url:
                    servicios.append({
                        'title': rec.title,
                        'abstract': rec.abstract,
                        'url': url,
                        'tipo': tipo
                    })
    except Exception as e:
        print(f"No se pudo conectar al CSW de la IDEE: {e}")

    print(f"Se han obtenido {len(servicios)} servicios con URL")
    return servicios
class serviciosIDEE2QGIS:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'serviciosIDEE2QGIS_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&serviciosIDEE2QGIS')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('serviciosIDEE2QGIS', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToWebMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/serviciosIDEE2QGIS/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginWebMenu(
                self.tr(u'&serviciosIDEE2QGIS'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = serviciosIDEE2QGISDialog()

            # Conectar el botón OK del button_box al método que añade capas
            self.dlg.button_box.accepted.connect(self.add_selected_services_to_map)

            # Llenar la tabla con los servicios
            self.populate_table()

        # Mostrar el diálogo
        self.dlg.show()
        self.dlg.raise_()


        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
    
    def populate_table(self):
        servicios = get_idee_services(batch_size=50)
        self.dlg.tableWidget.setRowCount(len(servicios))

        for i, serv in enumerate(servicios):
            # Columna 0: Checkbox
            checkbox = QCheckBox()
            checkbox.setChecked(False)
            self.dlg.tableWidget.setCellWidget(i, 0, checkbox)

            # Columna 1: Tipo de servicio
            tipo = "WMS" if any('WMS' in r['scheme'] for r in getattr(serv, 'references', [])) else "WFS"
            self.dlg.tableWidget.setItem(i, 1, QTableWidgetItem(tipo))

            # Columna 2: Nombre
            nombre_item = QTableWidgetItem(serv['title'])
            nombre_item.setData(Qt.UserRole, serv['url'])  # guardamos URL
            self.dlg.tableWidget.setItem(i, 2, nombre_item)

            # Columna 3: Descripción
            self.dlg.tableWidget.setItem(i, 3, QTableWidgetItem(serv['abstract']))
    
    def add_selected_services_to_map(self):
        for row in range(self.dlg.tableWidget.rowCount()):
            checkbox = self.dlg.tableWidget.cellWidget(row, 0)
            if checkbox is not None and checkbox.isChecked():
                item = self.dlg.tableWidget.item(row, 2)  # Columna con el nombre
                url = item.data(Qt.UserRole)
                nombre = item.text()

                if url is None:
                    print(f"Servicio {nombre} no tiene URL")
                    continue

                # Detectamos tipo de servicio
                tipo_item = self.dlg.tableWidget.item(row, 1)
                tipo = tipo_item.text() if tipo_item else "WMS"

                if tipo.upper() == "WMS":
                    layer = QgsRasterLayer(url, nombre, "wms")
                else:
                    layer = QgsVectorLayer(url, nombre, "WFS")

                if layer.isValid():
                    QgsProject.instance().addMapLayer(layer)
                else:
                    print(f"Capa {nombre} no es válida")


